.TH cara 8 "Mar 21, 2012" "cara 0.1.0" "Cara package manager"
.SH NAME
cara \- package manager for Caroline Linux

.SH SYNOPSIS
cara [\fB\-\-help\fR|\fB\-\-usage\fR|\fB\-\-version\fR] <\fIcommand\fR> [args]

.SH BASIC OPTIONS
.SS \-\-help
Show help with info about available commands, bug address and usage.
.SS \-\-version
Prints version and copyright note.
.SS \-\-usage
Output usage info.

.SH COMMANDS
Below are listed all commands available to use. Their short list could be achieved by running 
.BR cara\ \-\-help .
.SS installs
Installs a package. Additional options are listed below.
.
.TP
.B \-v, \-\-pkg\-version=\fIarg\fR
Set the packages version to
.IR arg .
If this option is not specified, cara will install the newest possible one.

.SH AUTHOR
.nf
Szymon Urbaś <urbas@hush.ai>
.fi
